name: "Validate PR Against JIRA with Mistral"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate-jira:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          # pin to v2 for CommonJS fetch support
          npm install @actions/core @actions/github node-fetch@2.6.9

      - name: Run PR Validator
        env:
          GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          JIRA_HOST:       ${{ secrets.JIRA_HOST }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN:  ${{ secrets.JIRA_API_TOKEN }}
        run: node .github/scripts/validate_pr.js
